Update jenkinsfile

diff --git a/tools/jenkinsfile b/tools/jenkinsfile
--- a/tools/jenkinsfile
+++ b/tools/jenkinsfile
@@ -7,12 +7,28 @@ pipeline {
                 echo 'Hello World'
             }
         }
+        stage('Check Docker') {
+            steps {
+                script {
+                    // Check if Docker is installed
+                    def dockerCheck = sh(script: 'which docker || echo "not found"', returnStdout: true).trim()
+                    
+                    if (dockerCheck == "not found") {
+                        echo 'Docker not found, installing...'
+                        sh '''
+                            sudo apt-get update
+                            sudo apt-get install -y docker.io
+                        '''
+                    } else {
+                        echo 'Docker is already installed'
+                    }
+                }
+            }
+        }
         stage('Docker Login') {
             steps {
                 script {
-                    // Use the credentials saved in Jenkins (replace 'docker-hub-credentials' with your credential ID)
                     withCredentials([usernamePassword(credentialsId: 'b91ccd61-788f-4cb4-92d9-fc89325337b6', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
-                        // Perform docker login
                         sh 'docker login -u $DOCKER_USER -p $DOCKER_PASS'
                     }
                 }
